apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: mq-from-pipeline
  namespace: mq
spec:
  license:
    accept: true
    license: L-RJON-BN7PN3
    use: NonProduction
  queueManager:
    name: MQAIA01
    storage:
      queueManager:
        type: ephemeral
    image: image-registry.openshift-image-registry.svc:5000/mq/mq-via-pipeline
    imagePullPolicy: Always
  version: 9.2.0.0-r1
  web:
    enabled: true